name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Ensure dist folder exists
        run: mkdir -p dist

      - name: print dist folder
        run: ls -la dist

      - name: Build CSS
        run: npm run build

      - name: Remove dist ignore for deploy
        run: sed -i '/^dist\/$/d' .gitignore

      - name: Stage built files
        run: git add dist -f

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: website
          clean: true
